### PR TITLE
Update for t9

### PR DESCRIPTION
**Pull request by Misaka13514**
sources:

- images, mission names, equipment names
  https://bluearchive.wikiru.jp/?26章
  - 0.5 size images are resized by [ImageMagick](https://imagemagick.org/script/command-line-processing.php#Inline%20Image%20Resize).

- mission drops
  https://bluearchive.fandom.com/wiki/Mission/Normal_Mission
  - Not sure about the 22.5% entry, using 15% instead. Review required.

### CODE REVIEW

**Comment by Misaka13514** [comment]
Rebasing to main branch to make CI happy...

**Comment by edwardez** [comment]
Thanks! Data looks mostly good to me, but just the order of the json is a bit off. 

The json is generated from a script by parsing what was in SchaleDB(images are from there as well), I just added you to the private data repo(the code is not up to my standard to pushlish as open-source hence private) and have updated json in that repo, you can find the updated json under `result/*.json`, would you mind doing a sanity check then merging those json with your pr? So that next time when we need to update json it's easier to confirm the diff(if order of the data if different from the generated json, next time it'll be harder to compare the diff).

**Comment by Misaka13514** [comment]
I looked at your private repository and I'm not sure what I should do. Do you want to copy the 2 json files in the `result` folder in your `bas-data` repository to my branch? Or do you want to copy images in this repository to `bas-data`? (If you can make these changes faster than I can understand, you can push to my branch.)

**Comment by edwardez** [comment]
> I looked at your private repository and I'm not sure what I should do. Do you want to copy the 2 json files in the `result` folder in your `bas-data` repository to my branch? Or do you want to copy images in this repository to `bas-data`? (If you can make these changes faster than I can understand, you can push to my branch.)

oh! the reasonI share the repo with you instead of just giving you the data, is mostly because if the next time you want to update the json, you can run scripts in that repo as well :)

Images are fine, please just copy json from that repo as-is to your pr and do some sanity check(basically just use json from that repo). I updated `bas-data` json and it looks fine to me, but since I have not touched this repo for a long while I’d like to have a double-check from you. 

lmk if you still have any questions!

**Comment by Misaka13514** [comment]
Current snapshot: N26
Screenshot From 2024-11-19 21-56-59
Screenshot From 2024-11-19 21-55-55
26-2 ~ 26-5 item not correct, fixing...
(Keeping the difference on 26-1: using 15% instead of 22.5% entry?)

**Comment by Misaka13514** [comment]
There are still some differences between current campaigns.json and https://bluearchive.fandom.com/wiki/Mission/Normal_Mission, I am not sure not to do. Data is from https://github.com/SchaleDB/SchaleDB and we don't have other credible sources?

I just remembered that the current data cannot be modified directly because it is generated, reverting 16c5541

**Comment by Misaka13514** [comment]
Checked current N26 stage drops are same as [schaledb.com](https://schaledb.com/stage/1261101).

**Comment by edwardez** [comment]
Thanks for looking into it! I think the fandom wiki has their data messed up, just checked the in-game drops. schaledb at least has the correct item drops but fandom wiki has something that's completely off.
image


image

> using 15% instead of 22.5% entry

yeah, 22.5% on schaledb is a sum up of two items(`22.5*2/3=15, 22.5*1/3=7.5`), it's just the same data got displayed two different ways. We break it down while schaledb sums it up.
image

> we don't have other credible sources

Not I am aware of :( schaledb has been trustworthy over the years afaik

**Comment by edwardez** [comment]
Deployed to https://fishfood.sensei.help/ 

will deploy to prod after some time

**Pull request merged**
